### ISSUE TITLE
Organization of files and Frameworks

### ISSUE THREAD

**Issue by drahosp** [fjolnir/TLC#1]
Please consider organizing the project as follows:

``` cmd
/tlc
 + /objc
 |  +  /init.lua # ObjC core definitions, current tlc - framework specific types and functions
 |  +  /Foundation.lua # Foundation specific ffi.load and convinience functions such as NSString, NSArray and NSObject utils
 |  +  /CoreFoundation.lua # Same for CoreFoundation framework
 |  +  /AppKit.lua # etc.
 |  +  ... 
 |
 + ...
```

This way frameworks can be loaded using require, eg: `require "objc.AppKit"` which can also ensure that dependent frameworks are loaded by requiring the Foundation frameworks. The `objc.loadFramework` function can require the framework file if it exists and then fall back to the current implementation for other frameworks. Keeping the files in the `objc` directory will also make installing the project much easier.

**Comment by fjolnir** [comment]
I took your advice and changed the directory structure.
Do let me know if it makes sense or not.

**Comment by drahosp** [comment]
Looks much better now. It would be great to keep the `objc/init.lua` contents and definitions specific only to the [ObjC Runtime](https://developer.apple.com/library/mac/#documentation/Cocoa/Reference/ObjCRuntimeRef/Reference/reference.html). Similarly you could move  [Foundation Framework](https://developer.apple.com/library/mac/#documentation/Cocoa/Reference/Foundation/ObjC_classic/_index.html#//apple_ref/doc/uid/20001091) specific definitions and helper functions (NSArr, NSStr ...) to `objc/Foundation.lua`. Same would apply to other frameworks such as the [CoreFoundation](http://developer.apple.com/library/mac/#documentation/CoreFoundation/Reference/CoreFoundation_Collection/_index.html) and its `CF*` types. The `objc/utilis.lua` can be merged into `objc/init.lua` as it is not framework specific. This way the project would follow the organization of Apple Frameworks nicely.

**Comment by fjolnir** [comment]
Right now that's pretty much how it's done, all C functions/types (apart from the objc runtime ones) should now be loaded using BridgeSupport.lua.
However I can't extract the type->object conversion functions as the core uses them. And I just can't imagine a use case of the bridge where you wouldn't want to be able to convert lua types to objects so, making it a separate require() would just be cumbersome.
