### ISSUE TITLE
How to pass objects back and forth through the bridge?

### ISSUE THREAD

**Issue by rraallvv** [fjolnir/TLC#5]
Is it posible to do something like this:

```
MyClass *myObj = [[MyClass alloc] init];
lua_pushlightuserdata (L, myObj);
lua_setglobal(L, "myObj");
lua_dostring(L,
  "local objc = require'objc' \n"
  "local ffi = require'ffi' \n"
  "local myLuaObj = ffi.cast(ffi.typeof'id', myObj) \n"
  "myLuaObj:doSomething() \n"
);
```

I would like to be able to pass objects back and forth between ObjC and the Lua virtual machine.

**Comment by fjolnir** [comment]
I don't see why that wouldn't work.

But I've personally always passed things around via objc messages

**Comment by rraallvv** [comment]
It's working now, I don't know what was wrong, somehow I managed to screw the test app I was working on.
I'm closing this then.
Thanks for the quick reply.
